# Generated by Django 4.1.1 on 2022-11-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('avg_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('private', models.BooleanField(default=True)),
                ('avatar', models.URLField(blank=True, default='')),
            ],
        ),
    ]
